import { Box, styled } from "@mui/material";

const DashboardStyle = styled(Box)(({ theme }) => ({
  margin: "0px 8px",
  ".appbarStyle": {
    display: "flex",
    margin: "6px",
    justifyContent: "space-between",
  },
  ".textNameStyle": {
    color: "#8181A5",
    fontFamily: "League Spartan",
    fontWeight: 700,
    fontSize: "14px",
    fontStyle: "normal",
  },
  ".protfoliContainerStyle": {
    background: `linear-gradient(45deg, white, transparent 250%)right,repeating-linear-gradient(45deg, transparent, #41C0D2 6px, white 10px)`,
    margin: "6px",
    marginTop: "18px",
    display: "flex",
    flexDirection: "column",
    padding: "16px 14px",
    borderRadius: "8px",
  },
  ".boxContainerStyle": {
    margin: "6px",
    marginTop: "12px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: "16px 14px",
    border: "2px solid #E9DCFA",
    borderRadius: "8px",
  },
  ".loanTextStyle": {
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    color: "#696D7C",
  },
  ".healthyTextStyle": {
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "24px",
    lineHeight: "24px",
    color: "#5516AA",
  },
  ".learnMoreButtonStyle": {
    padding: "8px 12px",
    gap: "10px",
    background: "#E7F7F9",
    opacity: "0.8",
    borderRadius: "150px",
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "12px",
    lineHeight: "16px",
    color: "#41C0D2",
    textTransform: "none",
    "&: hover": {
      background: "#41C0D2",
      color: "#E7F7F9",
    },
  },
  ".creditBtnStyle": {
    width: "100%",
    background: "#5516AA",
    borderRadius: "150px",
    padding: "16px",
    marginTop: "16px",

    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "16px",
    textTransform: "none",
    "&: hover": {
      color: "#5516AA",
      background: "#ffffff",
    },
  },
  ".fundsContainerStyle": {
    margin: "6px",
    marginTop: "12px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: "16px 15px",
  },
  ".fundsTextStyle": {
    marginTop: "10px",
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "16px",
    color: "#8181A5",
  },
  ".fundsButtonStyle": {
    background: "#FDE9EA",
    opacity: "0.8",
    borderRadius: "150px",
    padding: "8px 12px",
    gap: "10px",
    color: "#EF4F53",
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
    textTransform: "none",
    "&: hover": {
      color: "#FDE9EA",
      background: "#EF4F53",
    },
  },
  ".portfolioDivStyile": {
     display: "flex", justifyContent: "space-between" 
    },
  ".dataContainerStyle": {
    margin: "5px",
    marginTop: "12px",
    padding: "10px",
    border: "1.5px solid #E9DCFA",
    borderRadius: "8px",
  },
  ".textStyle": {
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "24px",
    color: "#1C1D21",
  },
  ".dataContainer": {
    display: "flex",
    flexDirection: "column",
    width: "50%",
    margin: "2px 8px",
  },
  ".dataKeyStyle": {
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "10px",
    lineHeight: "24px",
    color: "#8181A5",
  },
  ".dataValueStyle": {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "10px",
    lineHeight: "24px",
    color: "#1C1D21",
    textAlign: "left",
  },
  ".currentValueStyle": {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "12px",
    lineHeight: "24px",
    color: "#41C0D2",
    marginLeft: "-20px",
  },
  ".bottomNavigationContainer": {
    [theme.breakpoints.up("sm")]: {
      display: "flex",
      justifyContent: "center",
    },
  },
}));

export default DashboardStyle;
