import { Box, styled } from "@mui/material";

const PortfoliofetchStyle = styled(Box)(({ theme }) => ({
  ".backBtnStyle": {
    margin: "5px",
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "18px",
    color: "#1C1D21",
    textTransform: "none",
  },
  ".headingTextStyle": {
    marginTop: "25px",
    padding: " 0px 20px",
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "24px",
    lineHeight: "24px",
    color: "#1C1D21",
  },
  ".subHeadingTextStyle": {
    padding: "8px 25px",
    fontFamily: "League Spartan",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "16px",
    color: "#8181A5",
  },
  ".btnStyle": {
    margin: "auto",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-Between",
    alignItems: "center",
    padding: "16px 20px",
    background: "#F6F0FE",
    borderRadius: "150px",
    width: "90%",
    marginTop: "20px",
    color: "#5516AA",
    textTransform: "none",
    "&: hover": {
      color: "#F6F0FE",
      background: "#5516AA",
    },
  },
  ".btnTextStyle": {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "16px",
  },
  ".arrowBtnStyle": {
    border: "1.5px solid #BC91F6",
    color: "#BC91F6",
    borderRadius: "50%",
  },
  ".bottomContainerStyle": {
    position: "fixed",
    
    bottom: "0px",
    margin: "3% auto",
    left: 0,
    right: 0,
  },
  ".bottomTextStyle": {
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "16px",
    color: "#A1A1BC",
    margin: "1% auto",
    width: "60%",
    textAlign: "center",
  },
  ".bottomButtonStyle": {
    margin: "auto",
    display: "flex",
    padding: "16px",
    background: "#F6F6F6",
    borderRadius: "150px",
    width: "30%",
    marginTop: "20px",
    color: " #898989",
    textTransform: "none",
    fontFamily: "Lato",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "16px",
    "&: hover": {
      color: "#F6F0FE",
      background: "#5516AA",
    },
    [theme.breakpoints.down("sm")]: {
      width: "90%",
    },
  },
}));

export default PortfoliofetchStyle;
